### ISSUE TITLE
Branch policy not needed?

### ISSUE THREAD

**Issue by algattik** [toolboc/IoTEdge-DevOps#12]
Given the pipeline definition, a build automatically triggers on commits to any branch. Therefore, it seems the step of creating a branch policy can be removed; continuous integration is already achieved.

**Comment by toolboc** [comment]
You are correct due to the special way that the existence of [.azure-pipelines.yml](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-tutorial-pipeline) is handled, however, the intent here is to introduce the user to where this is all configured provided any changes would want to be made regarding branch to build from / retention period etc.
