### ISSUE TITLE
Azure IoT Edge For VSTS extension getting error while installing

### ISSUE THREAD

**Issue by shashikanthvnmmattapalli** [toolboc/IoTEdge-DevOps#2]
Hi,

While i try to install Azure IoT Edge For VSTS extension prompting as Task definition with id ......is a built-in task definition and cannot be replaced.

Please help me out to over come this issue.

**Comment by toolboc** [comment]
@shashikanthvnmmattapalli, the Azure IoT Edge Pipelines task was recently updated to [V2](https://github.com/microsoft/azure-pipelines-tasks/tree/20e77b1f6d7f1efbdd0cea2eab19553a179a5ce1/Tasks/AzureIoTEdgeV2) and is now included in installs of Azure DevOps  by default and no longer requires any additional installation steps. 

Due to this, it broke some of the functionality in this repo temporarily but it has all been updated now and should work with the current V2 task.  I was able to follow the current instructions to build all of the pipelines described without issue.  If you decide to take it for a spin, let me know how it works out!
